name: CI

on:
  workflow_dispatch:
    inputs:
      testPlanKey:
        description: 'TestPlan key from Xray'
        default: ''
        required: true
        type: string
      projectKey:
        description: 'Project key from Xray'
        default: ''
        required: true
        type: string
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Output Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm install
        npm i -D @playwright/test
        npx playwright install 
    - name: Run tests
      continue-on-error: true
      run: |  
        PLAYWRIGHT_JUNIT_OUTPUT_NAME=xray-report.xml npx playwright test
    - name: Output results file
      run: |
        cat xray-report.xml
    - name: "Import results to Xray"
      uses: mikepenz/xray-action@v2.4.5
      with:
         username: ${{ secrets.JIRA_USERNAME }}
         password: ${{ secrets.JIRA_PASSWORD }}
         xrayCloud: "false"
         xrayBaseUrl: ${{ secrets.JIRA_BASEURL }}
         testFormat: "junit"
         testPaths: "**/xray-report.xml"
         testPlanKey: "${{ inputs.testPlanKey }}"
         projectKey: "${{ inputs.projectKey }}"
         testEnvironments: "NODE_${{ matrix.node-version }}"
